version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn -B package --file pom.xml 
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/addressbook.jar
  discard-paths: yes
