steps:
  - name: gcr.io/$PROJECT_ID/increment_build_number
    id: build-number
    waitFor:
      - '-'
    args: [ 'gs://${_CONFIG_BUCKET}/${_BUILD_NAME}', '--major', '0', '--minor', '1' ]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - build-number
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook:$build_num", "--build-arg=JAR_FILE=target/addressbook.jar", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source .buildenv &&
        docker build -t gcr.io/$PROJECT_ID/addressbook:latest -t gcr.io/$PROJECT_ID/addressbook:$build_num .
images: ["gcr.io/$PROJECT_ID/addressbook"]

substitutions:
  _CONFIG_BUCKET: 'incrementbuild'
  _BUILD_NAME: 'addressbook'
