steps:
  - name: gcr.io/$PROJECT_ID/increment_build_number
    id: build-number
    waitFor:
      - '-'
    args: [ 'gs://${_CONFIG_BUCKET}/${_BUILD_NAME}', '--major', '0', '--minor', '1' ]
  - name: maven:3-jdk-8
    id: mvntest
    waitFor:
      - build-number
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    id: mvnpackage
    waitFor:
      - mvntest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]              
            
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - mvnpackage
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook:$build_num", "--build-arg=JAR_FILE=target/addressbook.jar", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source .buildenv &&
        docker build -t gcr.io/$PROJECT_ID/addressbook1:latest -t gcr.io/$PROJECT_ID/addressbook1:$build_num .
        
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    id: sshkey-host
    waitFor:
      - build-service
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      cp known_hosts.github /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    id: clone-manifestrepo
    waitFor:
      - sshkey-host
    args:
    - clone
    - --recurse-submodules
    - git@github.com:rakesh635/devops_manifest
    volumes:
    - name: 'ssh'
      path: /root/.ssh
      
  # modify the manifest file
  - name: gcr.io/cloud-builders/git
    id: generate-manifest
    waitFor:
      - clone-manifestrepo
    entrypoint: 'bash'
    args:
      - -c
      - |
        cd devops_manifest
        echo '----> '.${build_num}.' <----'
        
        sed -i "s/VERSIONNUMB/${build_num}/g" > kube/addressbook_deploy.yaml
        cat kube/addressbook_deploy.yaml        
  
  # This step pushes the manifest back to hello-cloudbuild-env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: push-manifest
    waitFor:
      - generate-manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        git config --global user.email "rakesh635@gmail.com"
        git config --global user.name "rakesh635"
        git add . && \
        git commit -m "Deploying image gcr.io/$PROJECT_ID/addressbook:${build_num}
        Built from commit ${COMMIT_SHA} of repository addressbook
        Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
        git push origin candidate 
images: ["gcr.io/$PROJECT_ID/addressbook"]

substitutions:
  _CONFIG_BUCKET: 'incrementbuild'
  _BUILD_NAME: 'addressbook'

availableSecrets:
  secretManager:
  - versionName: projects/287459854686/secrets/github_rakesh635/versions/latest
    env: 'SSH_KEY'
