steps:
  - name: gcr.io/$PROJECT_ID/increment_build_number
    id: build-number
    waitFor:
      - '-'
    args: [ 'gs://${_CONFIG_BUCKET}/${_BUILD_NAME}', '--major', '0', '--minor', '1' ]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - build-number
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook:$build_num", "--build-arg=JAR_FILE=target/addressbook.jar", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        source .buildenv &&
        docker build -t gcr.io/$PROJECT_ID/addressbook:latest -t gcr.io/$PROJECT_ID/addressbook:$build_num .
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clone env repository
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud source repos clone hello-cloudbuild-env && \
        cd hello-cloudbuild-env && \
        git checkout candidate && \
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
  # This step generates the new manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Generate manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" kubernetes.yaml.tpl | \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > hello-cloudbuild-env/kubernetes.yaml
  # This step pushes the manifest back to hello-cloudbuild-env
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Push manifest
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        cd hello-cloudbuild-env && \
        git add kubernetes.yaml && \
        git commit -m "Deploying image us-central1-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild:${SHORT_SHA}
        Built from commit ${COMMIT_SHA} of repository hello-cloudbuild-app
        Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
        git push origin candidate 
images: ["gcr.io/$PROJECT_ID/addressbook"]

substitutions:
  _CONFIG_BUCKET: 'incrementbuild'
  _BUILD_NAME: 'addressbook'
